services:
  db:
    image: postgres:17
    container_name: lang_map_db
    environment:
      POSTGRES_DB: lang_map
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: lang_map_nginx
    environment:
      - APP_PORT=2020 
      - SERVER_NAME=${SERVER_NAME:-localhost}
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lang_map_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro

  app:
    build:
      context: ./server/resource-server
      dockerfile: Dockerfile
    environment:
      - PORT=2020
    ports:
      - "2020:2020"
    volumes:
      - ./server/resource-server:/app
      - ./server/resource-server/node_modules:/app/node_modules
    depends_on:
      - db
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge