services:
  db:
    image: postgres:17
    container_name: lang_map_db
    environment:
      POSTGRES_DB: lang_map
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: lang_map_nginx
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lang_map_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge